### ISSUE TITLE
Bugs with maps

### ISSUE THREAD

**Issue by 4F-Beep** [EvoTM/EvoSC#151]
Congratulations for your work

**Describe the bug**
Bug with maps
Impossible to play some maps
i can add them
i can juke them
But i cant play them, they stay in jukebox

In log file, there's an error
[09:06:32] Hook->execute(): Exception: SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #5 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'evosc.pbs.score' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by (SQL: select `players`.`id`, `Login`, `Rating`, `Map`, `pbs`.`Score` from `players` left join `mx-karma` on `mx-karma`.`Player` = `players`.`id` and `mx-karma`.`Map` = 44 left join `pbs` on `pbs`.`player_id` = `players`.`id` where `players`.`id` in (17) group by `players`.`id`, `Login`, `Rating`, `Map`)

**Expected behavior**
Explain what should have happened, or not.

**To Reproduce**
Please explain what led to the issue.
Example:
[evosc_2021-05-15.txt](https://github.com/EvoTM/EvoSC/files/6483696/evosc_2021-05-15.txt)

**Screenshots/Logs**
If any available, add screenshots/logs to help explain your problem.

**EvoSC (please complete the following information):**
 - EvoSC-Version: [e.g. 0.87.x] (get with `php esc version`)
 - Game: TM² or TM2020

**When using git (please complete the following information):**
 - Current-Commit: [e.g. bb3eefb3622e864ad480641f281d4a2e4be50a69] (get with `git rev-parse HEAD`)

**Comment by 4F-Beep** [comment]
Server is ok without evosc

The problem is about my evosc

What you do you think about that?

Thanks for answer

**Comment by snixtho** [comment]
Your EvoSC version (0.99.7) is several months old, what happens if you update to the latest version, 0.99.22?

**Comment by 4F-Beep** [comment]
Thanks for your answer

I updated with "git pull"

Now, I have PHP fatal error

**Comment by 4F-Beep** [comment]
Here's the terminal
..................................................PHP Fatal error:  Uncaught Error: Class 'Mexitek\PHPColors\Color' not found in /home/sebastien/Bureau/TMserver/EvoSC/vendor/latte/latte/src/Latte/Engine.php(190) : eval()'d code:98
Stack trace:
#0 /home/sebastien/Bureau/TMserver/EvoSC/vendor/latte/latte/src/Latte/Runtime/Template.php(205): Templatee33b184567->main()
#1 /home/sebastien/Bureau/TMserver/EvoSC/vendor/latte/latte/src/Latte/Runtime/Template.php(247): Latte\Runtime\Template->render()
#2 /home/sebastien/Bureau/TMserver/EvoSC/vendor/latte/latte/src/Latte/Runtime/Template.php(351): Latte\Runtime\Template->Latte\Runtime\{closure}()
#3 /home/sebastien/Bureau/TMserver/EvoSC/vendor/latte/latte/src/Latte/Runtime/Template.php(250): Latte\Runtime\Template->filter()
#4 /home/sebastien/Bureau/TMserver/EvoSC/vendor/latte/latte/src/Latte/Engine.php(190) : eval()'d code(17): Latte\Runtime\Template->renderToContentType()
#5 /home/sebastien/Bureau/TMserver/EvoSC/vendor/latte/latte/src/Latte/Runtime/Template.php(205): Templatef5bf56786f->main()
#6 /home/sebastien/Bureau/TMserver/EvoSC in /home/sebastien/Bureau/TMserver/EvoSC/vendor/latte/latte/src/Latte/Engine.php(190) : eval()'d code on line 98

**Comment by brakerb** [comment]
You may want to call `composer install --no-dev -o` after pulling, to make sure you have all required packages installed.

**Comment by 4F-Beep** [comment]
Big thanks

**Comment by 4F-Beep** [comment]
But maps are not played

server is ok without evoSC

When EvoSC is running some maps cant be played :(

**Comment by 4F-Beep** [comment]
Someone have an idea about these maps not played?
Without evoSC, maps rotation is ok.

**Comment by 4F-Beep** [comment]
Here's error in log file
[09:06:32] Hook->execute(): Exception: SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #5 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'evosc.pbs.score' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by (SQL: select players.id, Login, Rating, Map, pbs.Score from players left join mx-karma on mx-karma.Player = players.id and mx-karma.Map = 44 left join pbs on pbs.player_id = players.id where players.id in (17) group by players.id, Login, Rating, Map)

Someone know what's is the problem?

**Comment by 4F-Beep** [comment]
Nobody knows about this error.

Need help :)

Thanks for return

**Comment by snixtho** [comment]
Which version of MySQL do you use?

**Comment by brakerb** [comment]
Please try with the latest develop version

**Comment by 4F-Beep** [comment]
thx for return,
i dont know about version, i installed  automaticly with linux
i ll try with the next

**Comment by 4F-Beep** [comment]
version (); donne
8.0.23 - ubuntu 20.04.1
