### ISSUE TITLE
Error during import of uaseco data

### ISSUE THREAD

**Issue by keplusplus** [EvoTM/EvoSC#23]
When I try to import uaseco data, I get the following stack trace:

php esc import:uaseco localhost db_name db_username db_password uaseco_
Importing players & stats
 0/2 [>---------------------------]   0% < 1 secPHP Fatal error:  Uncaught Error: Call to undefined method std
Class::update() in path\to\EvoSC\core\Commands\ImportUaseco.php:97
Stack trace:
#0 path\to\EvoSC\vendor\symfony\console\Command\Command.php(255): esc\Commands
\ImportUaseco->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Out
put\ConsoleOutput))
#1 path\to\EvoSC\vendor\symfony\console\Application.php(921): Symfony\Componen
t\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Con
sole\Output\ConsoleOutput))
#2 path\to\EvoSC\vendor\symfony\console\Application.php(273): Symfony\Componen
t\Console\Application->doRunCommand(Object(esc\Commands\ImportUaseco), Object(Symfony\Component\Console\Input\
ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 path\to\EvoSC\vendor\symfony\console\Application.php(149) in path\to\EvoSC\core\Commands\ImportUaseco.php on line 97

Fatal error: Uncaught Error: Call to undefined method stdClass::update() in path\to\EvoSC\core\Commands\ImportUaseco.php:97
Stack trace:
#0 path\to\EvoSC\vendor\symfony\console\Command\Command.php(255): esc\Commands
\ImportUaseco->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Out
put\ConsoleOutput))
#1 path\to\EvoSC\vendor\symfony\console\Application.php(921): Symfony\Componen
t\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Con
sole\Output\ConsoleOutput))
#2 path\to\EvoSC\vendor\symfony\console\Application.php(273): Symfony\Componen
t\Console\Application->doRunCommand(Object(esc\Commands\ImportUaseco), Object(Symfony\Component\Console\Input\
ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 path\to\EvoSC\vendor\symfony\console\Application.php(149) in path\to\EvoSC\core\Commands\ImportUaseco.php on line 97

Uaseco works fine, so I don't think my data is corrupt.

**Comment by brakerb** [comment]
Hey, thanks for the post. I will look into it as soon as possible. It's likely that recent updates made the importer faulty.

**Comment by brakerb** [comment]
Hey @keplusplus please try with the latest update.
