### ISSUE TITLE
Class 'EvoSC\Controllers\' not found

### ISSUE THREAD

**Issue by MisterX2000** [EvoTM/EvoSC#56]
**Describe the bug**
Every time I start the Server this Error occurs.
`PHP Fatal error:  Uncaught Error: Class 'EvoSC\Controllers\' not found in C:\Server\Trackmania\EvoSC\core\Controllers\ControllerController.php:29`

System:
Windows 10 (Version 2004)
PHP 7.4.7

**Expected behavior**
To start without errors.

**To Reproduce**
1. Start TM2020 Server
2. Wait...
3. Start EvoSC

**Screenshots/Logs**
```
Executing migrations...
Nothing to migrate.
Connecting to server...
Connection established.
      ______           _____ ______
     / ____/  _______ / ___// ____/
    / __/| | / / __ \__ \/ /
   / /___| |/ / /_/ /__/ / /___
  /_____/|___/\____/____/\____/  0.91.0

[16:13:31] EscRun->execute(): Starting...
[16:13:31] Database::init(): Connecting to database...
[16:13:31] Database::init(): Database connected.
[16:13:32] TemplateController::loadTemplates(): Loading templates...
[16:13:32] ChatController::init(): Chat router started.
[16:13:32] MapController::loadMaps(): Loading maps
..........
PHP Warning:  preg_replace(): Compilation failed: missing terminating ] for character class at offset 20 in C:\Server\Trackmania\EvoSC\core\Controllers\ControllerController.php on line 21
PHP Warning:  preg_replace(): Compilation failed: missing terminating ] for character class at offset 20 in C:\Server\Trackmania\EvoSC\core\Controllers\ControllerController.php on line 21
PHP Warning:  preg_replace(): Compilation failed: missing terminating ] for character class at offset 20 in C:\Server\Trackmania\EvoSC\core\Controllers\ControllerController.php on line 21
PHP Warning:  preg_replace(): Compilation failed: missing terminating ] for character class at offset 20 in C:\Server\Trackmania\EvoSC\core\Controllers\ControllerController.php on line 21
PHP Warning:  preg_replace(): Compilation failed: missing terminating ] for character class at offset 20 in C:\Server\Trackmania\EvoSC\core\Controllers\ControllerController.php on line 21
PHP Warning:  preg_replace(): Compilation failed: missing terminating ] for character class at offset 20 in C:\Server\Trackmania\EvoSC\core\Controllers\ControllerController.php on line 21
PHP Warning:  preg_replace(): Compilation failed: missing terminating ] for character class at offset 20 in C:\Server\Trackmania\EvoSC\core\Controllers\ControllerController.php on line 21
PHP Warning:  preg_replace(): Compilation failed: missing terminating ] for character class at offset 20 in C:\Server\Trackmania\EvoSC\core\Controllers\ControllerController.php on line 21
PHP Warning:  preg_replace(): Compilation failed: missing terminating ] for character class at offset 20 in C:\Server\Trackmania\EvoSC\core\Controllers\ControllerController.php on line 21
PHP Warning:  preg_replace(): Compilation failed: missing terminating ] for character class at offset 20 in C:\Server\Trackmania\EvoSC\core\Controllers\ControllerController.php on line 21
PHP Warning:  preg_replace(): Compilation failed: missing terminating ] for character class at offset 20 in C:\Server\Trackmania\EvoSC\core\Controllers\ControllerController.php on line 21
PHP Warning:  preg_replace(): Compilation failed: missing terminating ] for character class at offset 20 in C:\Server\Trackmania\EvoSC\core\Controllers\ControllerController.php on line 21
PHP Warning:  preg_replace(): Compilation failed: missing terminating ] for character class at offset 20 in C:\Server\Trackmania\EvoSC\core\Controllers\ControllerController.php on line 21
PHP Warning:  preg_replace(): Compilation failed: missing terminating ] for character class at offset 20 in C:\Server\Trackmania\EvoSC\core\Controllers\ControllerController.php on line 21
PHP Warning:  preg_replace(): Compilation failed: missing terminating ] for character class at offset 20 in C:\Server\Trackmania\EvoSC\core\Controllers\ControllerController.php on line 21
PHP Warning:  preg_replace(): Compilation failed: missing terminating ] for character class at offset 20 in C:\Server\Trackmania\EvoSC\core\Controllers\ControllerController.php on line 21
PHP Warning:  preg_replace(): Compilation failed: missing terminating ] for character class at offset 20 in C:\Server\Trackmania\EvoSC\core\Controllers\ControllerController.php on line 21
PHP Warning:  preg_replace(): Compilation failed: missing terminating ] for character class at offset 20 in C:\Server\Trackmania\EvoSC\core\Controllers\ControllerController.php on line 21
PHP Warning:  preg_replace(): Compilation failed: missing terminating ] for character class at offset 20 in C:\Server\Trackmania\EvoSC\core\Controllers\ControllerController.php on line 21
PHP Warning:  preg_replace(): Compilation failed: missing terminating ] for character class at offset 20 in C:\Server\Trackmania\EvoSC\core\Controllers\ControllerController.php on line 21
PHP Warning:  preg_replace(): Compilation failed: missing terminating ] for character class at offset 20 in C:\Server\Trackmania\EvoSC\core\Controllers\ControllerController.php on line 21
PHP Fatal error:  Uncaught Error: Class 'EvoSC\Controllers\' not found in C:\Server\Trackmania\EvoSC\core\Controllers\ControllerController.php:29
Stack trace:
#0 C:\Server\Trackmania\EvoSC\core\Commands\EscRun.php(164): EvoSC\Controllers\ControllerController::loadControllers()
#1 C:\Server\Trackmania\EvoSC\vendor\symfony\console\Command\Command.php(255): EvoSC\Commands\EscRun->execute()
#2 C:\Server\Trackmania\EvoSC\vendor\symfony\console\Application.php(1000): Symfony\Component\Console\Command\Command->run()
#3 C:\Server\Trackmania\EvoSC\vendor\symfony\console\Application.php(271): Symfony\Component\Console\Application->doRunCommand()
#4 C:\Server\Trackmania\EvoSC\vendor\symfony\console\Application.php(147): Symfony\Component\Console\Application->doRun()
#5 C:\Server\Trackmania\EvoSC\esc(63): Symfony\Component\Console\Application->run()
#6 {main}
  thrown in C:\Server\Trackmania\EvoSC\core\Controllers\ControllerController.php on line 29
```

**EvoSC:**
 - EvoSC-Version: 0.91.0

**When using git:**
 - Current-Commit: c4ec61648c97b72f425cbfe6296bf803c9b2ed35

**Comment by brakerb** [comment]
Currently EvoSC is only fully supported on Linux systems. Windows support will come, but I cant not give an estimate when.
