### ISSUE TITLE
MxDetails not retrieving data for TM2020 tracks

### ISSUE THREAD

**Issue by mantazzo** [EvoTM/EvoSC#70]
**Describe the bug**
MxDetails fails to retrieve data for tracks in TM2020. While using the "GET" feature, the app gets thrown "400 Bad Request" errors (which also bugs the app a bit by not showing Map Details window), while opening the same links in the browser works well.

**Expected behavior**
Normally, it should get the details for the track, and also should open the Map Details window when required.

**To Reproduce**
Load a track, check the log to see "400 Bad Request" errors. Same happens when I try to press the "Details" button in the UI.

**Screenshots/Logs**
```
[15:14:52] EvoSC\Classes\RestClient::get(): GET: https://trackmania.exchange/api/maps/get_map_info/multi/159XBIpjid7Wh4mjIRQ6wazyme4
[15:14:53] EvoSC\Classes\Hook->execute(): Exception: Client error: `GET https://trackmania.exchange/api/maps/get_map_info/multi/159XBIpjid7Wh4mjIRQ6wazyme4` resulted in a `400 Bad Request` response:
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Bad Reques (truncated...)

#0 C:\Users\manta\git\EvoSC-Dev\vendor\guzzlehttp\guzzle\src\Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 C:\Users\manta\git\EvoSC-Dev\vendor\guzzlehttp\promises\src\Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 C:\Users\manta\git\EvoSC-Dev\vendor\guzzlehttp\promises\src\Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array)
#3 C:\Users\manta\git\EvoSC-Dev\vendor\guzzlehttp\promises\src\TaskQueue.php(47): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#4 C:\Users\manta\git\EvoSC-Dev\vendor\guzzlehttp\guzzle\src\Handler\CurlMultiHandler.php(118): GuzzleHttp\Promise\TaskQueue->run()
#5 C:\Users\manta\git\EvoSC-Dev\vendor\guzzlehttp\guzzle\src\Handler\CurlMultiHandler.php(145): GuzzleHttp\Handler\CurlMultiHandler->tick()
#6 C:\Users\manta\git\EvoSC-Dev\vendor\guzzlehttp\promises\src\Promise.php(246): GuzzleHttp\Handler\CurlMultiHandler->execute(true)
#7 C:\Users\manta\git\EvoSC-Dev\vendor\guzzlehttp\promises\src\Promise.php(223): GuzzleHttp\Promise\Promise->invokeWaitFn()
#8 C:\Users\manta\git\EvoSC-Dev\vendor\guzzlehttp\promises\src\Promise.php(267): GuzzleHttp\Promise\Promise->waitIfPending()
#9 C:\Users\manta\git\EvoSC-Dev\vendor\guzzlehttp\promises\src\Promise.php(225): GuzzleHttp\Promise\Promise->invokeWaitList()
#10 C:\Users\manta\git\EvoSC-Dev\vendor\guzzlehttp\promises\src\Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending()
#11 C:\Users\manta\git\EvoSC-Dev\vendor\guzzlehttp\guzzle\src\Client.php(182): GuzzleHttp\Promise\Promise->wait()
#12 C:\Users\manta\git\EvoSC-Dev\core\Classes\RestClient.php(78): GuzzleHttp\Client->request('GET', 'https://trackma...', Array)
#13 C:\Users\manta\git\EvoSC-Dev\core\Modules\MxDetails\MxDetails.php(120): EvoSC\Classes\RestClient::get('https://trackma...', Array)
#14 C:\Users\manta\git\EvoSC-Dev\core\Controllers\MapController.php(134): EvoSC\Modules\MxDetails\MxDetails::loadMxDetails(Object(EvoSC\Models\Map))
#15 [internal function]: EvoSC\Controllers\MapController::beginMap(Object(EvoSC\Models\Map))
#16 C:\Users\manta\git\EvoSC-Dev\core\Classes\Hook.php(79): call_user_func(Array, Object(EvoSC\Models\Map))
#17 C:\Users\manta\git\EvoSC-Dev\core\Classes\Hook.php(164): EvoSC\Classes\Hook->execute(Object(EvoSC\Models\Map))
#18 C:\Users\manta\git\EvoSC-Dev\core\Controllers\EventController.php(224): EvoSC\Classes\Hook::fire('BeginMap', Object(EvoSC\Models\Map))
#19 C:\Users\manta\git\EvoSC-Dev\core\Controllers\EventController.php(61): EvoSC\Controllers\EventController::mpBeginMap(Array)
#20 C:\Users\manta\git\EvoSC-Dev\core\Commands\EscRun.php(216): EvoSC\Controllers\EventController::handleCallbacks(Array)
#21 C:\Users\manta\git\EvoSC-Dev\vendor\symfony\console\Command\Command.php(255): EvoSC\Commands\EscRun->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 C:\Users\manta\git\EvoSC-Dev\vendor\symfony\console\Application.php(1000): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 C:\Users\manta\git\EvoSC-Dev\vendor\symfony\console\Application.php(271): Symfony\Component\Console\Application->doRunCommand(Object(EvoSC\Commands\EscRun), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 C:\Users\manta\git\EvoSC-Dev\vendor\symfony\console\Application.php(147): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 C:\Users\manta\git\EvoSC-Dev\esc(59): Symfony\Component\Console\Application->run()
#26 {main}
[15:14:53] EvoSC\Classes\Hook->execute(): ["EvoSC\\Controllers\\MapController","beginMap"]
```

**EvoSC (please complete the following information):**
 - EvoSC-Version: 0.93.26 (technically 27, since it's the current latest build from develop branch)

**When using git (please complete the following information):**
 - Current-Commit: 667cbe0cf7a7c122f306a371c79719d46e68ffe0

**Comment by mantazzo** [comment]
Can also add (after testing) that the same issue happens with MusicClient - throws me a 400 Bad Request error with a correct link.

**Comment by brakerb** [comment]
Fixed in latest release
