### ISSUE TITLE
EvoSC crashes after restart

### ISSUE THREAD

**Issue by StevenKowalzik** [EvoTM/EvoSC#73]
**Describe the bug**
After using the restart-evo command on the Server, Chat is getting spammend and Evo will not properly start.

**Expected behavior**
Evo should start properly.

**To Reproduce**
using //restart-evosc after a fresh installation.

**Screenshots/Logs**

```[10:22:26] ChatMessage->sendAll():  EvoSC v0.94.3 is restarting.
[10:22:26] restart_evosc(): Old process is terminating.
Error in /app/core/global-functions.php on Line 419
Call to undefined function pcntl_exec()
===============================================================================
#0 /app/core/Commands/EscRun.php(256): restart_evosc()
#1 /app/core/Classes/ChatCommand.php(176): EvoSC\Commands\EscRun::EvoSC\Commands\{closure}(Object(EvoSC\Models\Player), '//restart-evosc')
#2 /app/core/Controllers/EventController.php(130): EvoSC\Classes\ChatCommand->execute(Object(EvoSC\Models\Player), '//restart-evosc')
#3 /app/core/Controllers/EventController.php(57): EvoSC\Controllers\EventController::mpPlayerChat(Array)
#4 /app/core/Commands/EscRun.php(218): EvoSC\Controllers\EventController::handleCallbacks(Array)
#5 /app/vendor/symfony/console/Command/Command.php(255): EvoSC\Commands\EscRun->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /app/vendor/symfony/console/Application.php(1000): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /app/vendor/symfony/console/Application.php(271): Symfony\Component\Console\Application->doRunCommand(Object(EvoSC\Commands\EscRun), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /app/vendor/symfony/console/Application.php(147): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /app/esc(59): Symfony\Component\Console\Application->run()
#10 {main}```

**EvoSC (please complete the following information):**
 - 0.94.3

**Comment by brakerb** [comment]
> Currently, this module will not function on non-Unix platforms (Windows).

https://www.php.net/manual/en/pcntl.installation.php

Apparently pcntl_exec is not available on windows hosts, I'll look if I can find an alternative.

**Comment by StevenKowalzik** [comment]
I'm not on Windows, 
ill try to install that php module then. ty

**Comment by brakerb** [comment]
I've added a check for the existence of pcntl_exec. If it's not available, it will use exec to start a new instance and kill the old one. That will lead to a new PID.

pcntl_exec allows to restart the process and keep the PID, which is important for our monitoring software.
